# Setup
title:        Código Orientado a Investimentos
tagline:      Tecnologias e Técnicas em Programação e Investimentos
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Miguel Eichler
  url:        https://migueleichler.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
